import { readFileSync } from 'fs';
import {
  formatPct, formatK,
  cssClass, qClass,
  formatDateMeta, formatEdition, formatDateFull
} from './utils.js';

export function buildHTML({ market, bcb, fred, analysis }) {
  let html;
  try {
    html = readFileSync('./template/morning-call.html', 'utf8');
  } catch {
    console.error('[buildHTML] Template não encontrado');
    process.exit(1);
  }

  const hoje = new Date();

  const r = {
    DATA_DIA:    String(hoje.getDate()),
    DATA_META:   formatDateMeta(hoje),
    EDICAO:      formatEdition(hoje),
    DATA_FULL:   formatDateFull(hoje),

    MANCHETE:          analysis?.manchete ?? 'Morning Call ' + formatDateFull(hoje),
    PANORAMA_P1:       analysis?.panorama_p1 ?? '',
    PANORAMA_P2:       analysis?.panorama_p2 ?? '',
    SINTESE_JUROS:     analysis?.sintese?.juros ?? '',
    SINTESE_BOLSA:     analysis?.sintese?.bolsa ?? '',
    SINTESE_CAMBIO:    analysis?.sintese?.cambio ?? '',
    SINTESE_CATALISADOR: analysis?.sintese?.catalisador ?? '',

    IBOV_FECH_VAL: market.ibov?.prevClose?.toLocaleString('pt-BR') ?? '--',
    IBOV_FECH_CHK: formatPct(market.ibov?.changePercent),
    IBOV_FECH_CSS: cssClass(market.ibov?.changePercent),
    IBOV_NOW_VAL:  market.ibov?.value?.toLocaleString('pt-BR') ?? '--',
    IBOV_NOW_CHK:  formatPct(market.ibov?.changePercent),
    IBOV_NOW_CSS:  cssClass(market.ibov?.changePercent),
    USDBRL_VAL:    bcb.cambio?.valor?.toFixed(4) ?? '--',
    USDBRL_CHK:    '--',
    USDBRL_CSS:    'cneu',
    SP500F_VAL:    market.sp500f?.value?.toLocaleString('en-US') ?? '--',
    SP500F_CHK:    formatPct(market.sp500f?.changePercent),
    SP500F_CSS:    cssClass(market.sp500f?.changePercent),
    BRENT_VAL:     market.brent?.value?.toFixed(2) ?? '--',
    BRENT_CHG:     formatPct(market.brent?.changePercent),
    BRENT_CSS:     cssClass(market.brent?.changePercent),
    SELIC_VAL:     `${bcb.selic ?? '--'}%`,
    VIX_VAL:       market.vix?.value?.toFixed(2) ?? '--',
    VIX_CHG:       formatPct(market.vix?.changePercent),
    VIX_CSS:       cssClass(market.vix?.changePercent),
    BTC_VAL:       market.bitcoin?.value?.toLocaleString('en-US') ?? '--',
    BTC_CHG:       formatPct(market.bitcoin?.changePercent),
    BTC_CSS:       cssClass(market.bitcoin?.changePercent),
    DOW30F_VAL:    market.dow30f?.value?.toLocaleString('en-US') ?? '--',
    DOW30F_CHG:    formatPct(market.dow30f?.changePercent),
    DOW30F_Q:      qClass(market.dow30f?.changePercent),
    SP500F_Q_VAL:  market.sp500f?.value?.toLocaleString('en-US') ?? '--',
    SP500F_Q_CHG:  formatPct(market.sp500f?.changePercent),
    SP500F_Q:      qClass(market.sp500f?.changePercent),
    NASDAQ_VAL:    market.nasdaq?.value?.toLocaleString('en-US') ?? '--',
    NASDAQ_CHG:    formatPct(market.nasdaq?.changePercent),
    NASDAQ_Q:      qClass(market.nasdaq?.changePercent),
    RTF_VAL:       market.rtf?.value?.toLocaleString('en-US') ?? '--',
    RTF_CHG:       formatPct(market.rtf?.changePercent),
    RTF_Q:         qClass(market.rtf?.changePercent),
    VIX_Q_VAL:     market.vix?.value?.toFixed(2) ?? '--',
    VIX_Q_CHG:     formatPct(market.vix?.changePercent),
    VIX_Q:         qClass(market.vix?.changePercent),
    DAX_VAL:       market.dax?.value?.toLocaleString('de-DE') ?? '--',
    DAX_CHG:       formatPct(market.dax?.changePercent),
    DAX_Q:         qClass(market.dax?.changePercent),
    FTSE_VAL:      market.ftse?.value?.toLocaleString('en-US') ?? '--',
    FTSE_CHG:      formatPct(market.ftse?.changePercent),
    FTSE_Q:        qClass(market.ftse?.changePercent),
    CAC40_VAL:     market.cac40?.value?.toLocaleString('fr-FR') ?? '--',
    CAC40_CHG:     formatPct(market.cac40?.changePercent),
    CAC40_Q:       qClass(market.cac40?.changePercent),
    T2Y_VAL:       market.t2y?.value ? `${market.t2y.value.toFixed(3)}%` : '--',
    T2Y_CHG:       formatPct(market.t2y?.changePercent),
    T2Y_Q:         qClass(market.t2y?.changePercent),
    T10Y_VAL:      market.t10y?.value ? `${market.t10y.value.toFixed(3)}%` : '--',
    T10Y_CHG:      formatPct(market.t10y?.changePercent),
    T10Y_Q:        qClass(market.t10y?.changePercent),
    T30Y_VAL:      market.t30y?.value ? `${market.t30y.value.toFixed(3)}%` : '--',
    T30Y_CHG:      formatPct(market.t30y?.changePercent),
    T30Y_Q:        qClass(market.t30y?.changePercent),
    BRENT_Q_VAL:   market.brent?.value ? `US$ ${market.brent.value.toFixed(2)}` : '--',
    BRENT_Q_CHG:   formatPct(market.brent?.changePercent),
    BRENT_Q:       qClass(market.brent?.changePercent),
    WTI_VAL:       market.wti?.value ? `US$ ${market.wti.value.toFixed(2)}` : '--',
    WTI_CHG:       formatPct(market.wti?.changePercent),
    WTI_Q:         qClass(market.wti?.changePercent),
    GOLD_VAL:      market.gold?.value ? `US$ ${market.gold.value.toLocaleString('en-US')}` : '--',
    GOLD_CHG:      formatPct(market.gold?.changePercent),
    GOLD_Q:        qClass(market.gold?.changePercent),
    SILVER_VAL:    market.silver?.value ? `US$ ${market.silver.value.toFixed(2)}` : '--',
    SILVER_CHG:    formatPct(market.silver?.changePercent),
    SILVER_Q:      qClass(market.silver?.changePercent),
    COPPER_VAL:    market.copper?.value ? `US$ ${market.copper.value.toFixed(4)}` : '--',
    COPPER_CHG:    formatPct(market.copper?.changePercent),
    COPPER_Q:      qClass(market.copper?.changePercent),
    DXY_VAL:       market.dxy?.value?.toFixed(3) ?? '--',
    DXY_CHG:       formatPct(market.dxy?.changePercent),
    DXY_Q:         qClass(market.dxy?.changePercent),
    EURUSD_VAL:    market.eurusd?.value?.toFixed(4) ?? '--',
    EURUSD_CHG:    formatPct(market.eurusd?.changePercent),
    EURUSD_Q:      qClass(market.eurusd?.changePercent),
    GBPUSD_VAL:    market.gbpusd?.value?.toFixed(4) ?? '--',
    GBPUSD_CHG:    formatPct(market.gbpusd?.changePercent),
    GBPUSD_Q:      qClass(market.gbpusd?.changePercent),
    USDJPY_VAL:    market.usdjpy?.value?.toFixed(2) ?? '--',
    USDJPY_CHG:    formatPct(market.usdjpy?.changePercent),
    USDJPY_Q:      qClass(market.usdjpy?.changePercent),
    BTC_Q_VAL:     market.bitcoin?.value ? `US$ ${market.bitcoin.value.toLocaleString('en-US')}` : '--',
    BTC_Q_CHG:     formatPct(market.bitcoin?.changePercent),
    BTC_Q:         qClass(market.bitcoin?.changePercent),
    ETH_VAL:       market.ethereum?.value ? `US$ ${market.ethereum.value.toLocaleString('en-US')}` : '--',
    ETH_CHG:       formatPct(market.ethereum?.changePercent),
    ETH_Q:         qClass(market.ethereum?.changePercent),
    IPCA_RESULTADO:  bcb.ipca15?.atual ? `+${bcb.ipca15.atual}%` : '--',
    IPCA_ANTERIOR:   bcb.ipca15?.anterior ? `+${bcb.ipca15.anterior}%` : '--',
    IPCA_12M:        bcb.ipca15?.acum12m ? `${bcb.ipca15.acum12m}%` : '--',
    FOCUS_IPCA:      bcb.focus?.ipca ? `${bcb.focus.ipca}%` : '--',
    FOCUS_SELIC:     bcb.focus?.selic ? `${bcb.focus.selic}%` : '--',
    LEITURA_IPCA_DRIVERS: analysis?.leitura_ipca?.drivers ?? '',
    LEITURA_IPCA_INTERPRETACAO: analysis?.leitura_ipca?.interpretacao ?? '',
    LEITURA_IPCA_IMPLICACAO: analysis?.leitura_ipca?.implicacao ?? '',
    CLAIMS_ATUAL:   fred.initialClaims?.atual ? formatK(fred.initialClaims.atual) : '--',
    CLAIMS_ANTERIOR: fred.initialClaims?.anterior ? formatK(fred.initialClaims.anterior) : '--',
    CLAIMS_CONT:    fred.continuingClaims?.valor ? formatK(fred.continuingClaims.valor) : '--',
    LEITURA_CLAIM_DADOS: analysis?.leitura_claims?.dados ?? '',
    LEITURA_CLAIMS_FED:  analysis?.leitura_claims?.fed ?? '',
    GERADO_EM: new Date().toLocaleString('pt-BR', { timeZone: 'America/Sao_Paulo' }),
  };

  for (const [key, value] of Object.entries(r)) {
    html = html.replaceAll(`{{${key}}}`, value ?? '--');
  }
  return html;
}
